"""Types and constants for models."""
from .link_type import LinkType
from .constants import (
    SQLITE_MAX_VARIABLES,
    SQLITE_SAFE_BATCH_SIZE,
    SQLITE_SAFE_SELECT_CHUNK,
    DEFAULT_MAX_BACKUPS,
    BACKUP_RETRY_ATTEMPTS,
    BACKUP_RETRY_DELAY,
    PERFORMANCE_WARNING_THRESHOLD_MS,
    DEFAULT_QUERY_TIMEOUT,
    DEFAULT_ICON_PATH,
    EMPTY_ICON_PATH,
    VALID_POSITION_TABLES,
)

__all__ = [
    "LinkType",
    "SQLITE_MAX_VARIABLES",
    "SQLITE_SAFE_BATCH_SIZE",
    "SQLITE_SAFE_SELECT_CHUNK",
    "DEFAULT_MAX_BACKUPS",
    "BACKUP_RETRY_ATTEMPTS",
    "BACKUP_RETRY_DELAY",
    "PERFORMANCE_WARNING_THRESHOLD_MS",
    "DEFAULT_QUERY_TIMEOUT",
    "DEFAULT_ICON_PATH",
    "EMPTY_ICON_PATH",
    "VALID_POSITION_TABLES",
]
