# app/utils/ui_state/window_api.py
from __future__ import annotations

from typing import Protocol, Optional, Tuple, Iterable, Any
from PyQt6.QtGui import QAction


class SettingsAPI(Protocol):
    def get_theme(self) -> str: ...


class MainWindowAPI(Protocol):
    # Общие атрибуты
    settings: SettingsAPI
    undo_action: QAction | None
    redo_action: QAction | None

    # Методы структуры/категорий/ссылок, используемые меню
    def get_current_category_id(self) -> Optional[int]: ...
    def edit_structure_item(self, item: Any) -> None: ...
    def add_new_category(self) -> None: ...
    def show_link_dialog_for_category(self, category_id: int | None = None, link: dict | None = None) -> bool: ...

    # Таблица ссылок
    def get_link_at_row(self, row: int) -> dict | None: ...
    def open_link(self, link: dict) -> None: ...
    def toggle_link_favorite(self, link: dict) -> None: ...
    def copy_selected_links(self) -> None: ...
    def paste_links(self) -> None: ...
    def cut_selected_links(self) -> None: ...
    def select_all_links(self) -> None: ...
    def delete_selected_links(self) -> None: ...
    def show_note_dialog_for_link(self, link: dict) -> None: ...

    # Главное меню
    def show_settings_dialog(self) -> None: ...
    def show_file_search_dialog(self) -> None: ...
    def get_available_themes(self) -> Iterable[Tuple[str, str]]: ...
    def apply_theme(self, theme_name: str) -> None: ...
    def show_about_dialog(self) -> None: ...
    def create_undo_redo_actions(self) -> Tuple[QAction | None, QAction | None]: ...

    # Диалоги БД и системные
    def handle_import_browser_bookmarks(self) -> None: ...

    # Закрытие
    def close(self) -> None: ...
