exclude = ["dist", "logs"]

[lint]
select = ["F", "E", "I"]
extend-select = [
  "B",     # flake8-bugbear
  "C90",   # mccabe complexity
  "UP",    # pyupgrade
]
ignore = ["E501"]

[lint.mccabe]
max-complexity = 12