"""Константы TopBarLayoutManager, вынесенные в отдельный модуль.

Не меняют поведение. Используются менеджером как значения по умолчанию.
"""

DEFAULT_THROTTLE_MS = 32
DEFAULT_LOG_INFO = False
DEFAULT_MIN_SEARCH_WIDTH = 148
DEFAULT_MAX_RECENT = 10
DEFAULT_MAX_FAV = 10
DEFAULT_MAX_QUICK = 6
DEFAULT_MIN_RECENT = 0
DEFAULT_MIN_FAV = 0
DEFAULT_MIN_QUICK = 0
DEFAULT_NARROW_THRESHOLD = 380
DEFAULT_BUTTON_SIZE = 32
DEFAULT_SPACER_SIZE = 4

__all__ = [
    "DEFAULT_THROTTLE_MS",
    "DEFAULT_LOG_INFO",
    "DEFAULT_MIN_SEARCH_WIDTH",
    "DEFAULT_MAX_RECENT",
    "DEFAULT_MAX_FAV",
    "DEFAULT_MAX_QUICK",
    "DEFAULT_MIN_RECENT",
    "DEFAULT_MIN_FAV",
    "DEFAULT_MIN_QUICK",
    "DEFAULT_NARROW_THRESHOLD",
    "DEFAULT_BUTTON_SIZE",
    "DEFAULT_SPACER_SIZE",
]
